fragment CudaSelector on CudaSelector {
  computeCapability
  cudaVersion
  memory
  count
  cudaCores
}

fragment RocmSelector on RocmSelector {
  apiVersion
  apiThing
}

fragment CpuSelector on CPUSelector {
  minCount
  frequency
  arch
}

fragment RamSelector on RAMSelector {
  min
}

fragment OneApiSelector on OneApiSelector {
  oneapiVersion
}

fragment LabelSelector on LabelSelector {
  key
  value
}

fragment ListFlavour on Flavour {
  id
  name
  image {
    imageString
    buildAt
  }
  manifest
  requirements {
    key
    service
    description
    optional
  }
  repo {
    url
  }
  selectors {
    kind
    required
    weight
    ...CudaSelector
    ...RocmSelector
    ...CpuSelector
    ...RamSelector
    ...OneApiSelector
    ...LabelSelector
  }
}

fragment Flavour on Flavour {
  ...ListFlavour
  release {
    id
    version
    app {
      identifier
    }
    scopes
  }
}
